### ISSUE TITLE
[Question] Error regarding RuntimeError: CUDA error: misaligned address

### ISSUE THREAD

**Issue by yl3639** [MIC-DKFZ/nnDetection#171]
### :question: Question

import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([4, 32, 224, 224, 192], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv3d(32, 64, kernel_size=[3, 3, 3], padding=[1, 1, 1], stride=[2, 2, 2], dilation=[1, 1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    memory_format = Contiguous
    data_type = CUDNN_DATA_HALF
    padding = [1, 1, 1]
    stride = [2, 2, 2]
    dilation = [1, 1, 1]
    groups = 1
    deterministic = true
    allow_tf32 = true
input: TensorDescriptor 0x7e5f690
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 4, 32, 224, 224, 192, 
    strideA = 308281344, 9633792, 43008, 192, 1, 
output: TensorDescriptor 0x85f95a0
    type = CUDNN_DATA_HALF
    nbDims = 5
    dimA = 4, 64, 112, 112, 96, 
    strideA = 77070336, 1204224, 10752, 96, 1, 
weight: FilterDescriptor 0x89624a10
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 5
    dimA = 64, 32, 3, 3, 3, 
Pointer addresses: 
    input: 0x7f32be000000
    output: 0x7f3351000000
    weight: 0x7f347e143c00

Traceback (most recent call last):
  File "/data/yil/environment/anaconda3/envs/nnde/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/data/yil/work/bricks/nnDetection/nndet/utils/check.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/data/yil/work/bricks/nnDetection/scripts/preprocess.py", line 406, in main
    run(OmegaConf.to_container(cfg, resolve=True),
  File "/data/yil/work/bricks/nnDetection/scripts/preprocess.py", line 335, in run
    run_planning_and_process(
  File "/data/yil/work/bricks/nnDetection/scripts/preprocess.py", line 162, in run_planning_and_process
    plan_identifiers = planner.plan_experiment(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/experiment/v001.py", line 43, in plan_experiment
    plan_3d = self.plan_base_stage(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/experiment/base.py", line 234, in plan_base_stage
    architecture_plan = architecture_planner.plan(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/architecture/boxes/c002.py", line 127, in plan
    res = super().plan(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/architecture/boxes/base.py", line 346, in plan
    patch_size = self._plan_architecture(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/architecture/boxes/c002.py", line 205, in _plan_architecture
    _, fits_in_mem = self.estimator.estimate(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/estimator.py", line 127, in estimate
    res = self._estimate_mem_available(
  File "/data/yil/work/bricks/nnDetection/nndet/planning/estimator.py", line 154, in _estimate_mem_available
    fixed, dynamic = self.measure(shape=target_shape,
  File "/data/yil/work/bricks/nnDetection/nndet/planning/estimator.py", line 252, in measure
    network.cpu()
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 738, in cpu
    return self._apply(lambda t: t.cpu())
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/data/yil/environment/anaconda3/envs/nnde/lib/python3.8/site-packages/torch/nn/modules/module.py", line 738, in <lambda>
    return self._apply(lambda t: t.cpu())
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by mibaumgartner** [comment]
Does the first code snippet work without error?

**Comment by yl3639** [comment]
Thanks, it was an old error, got fixed after that :D
